language: java
jdk:
- oraclejdk8
install: mvn --version
before_script: "./.travis.version_if_tag.sh"
after_success: "./.travis.deploy_if_tag.sh"
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: LxBf+LzoRJTu50JcvegltG2M6DelYnN/sJRXwiSVRzXs2vcmrokb5I/LW2ORw5dzf3j5LtHnBeiNdcgD5xh2dqDkBncpQK1yVvPHa75oeagdWYUMk6KQBERzkHmuepiEy52sJPD88fgq1Es0QHqd54tZH4vbs0SS3QgQwupxrlNfRkCOMp1M9y4oa9hrMpKeRG572HP/BEsXp5in5++r1MOWy6fKp6mS0PXlM4xbHrXx4hPgcJ9KVVjV4tWT64eOt0goWpPwQvh5M1aguX5THs+xAfZRUDl8iA1RrSEjAkdOAN+qJ0l2r/8XvRVg35dfKaIg5NOiJ+S6tXPsvTxu5I1K2vB39FzLNFwkAinE7FRmy/XxvVDw0QosAoeCG2O5n6+RlXXCSi6LJ+NH06B0MxE6eUN+BUgi28aG/mjtEbwUrYiHf4nh0jsm7k7efG4UBGZXqPNc1p1Lj4IEMWUOpscJXP77jZPLz9vYIdEz9jxd830SfcTptNZOg3UmwsqRJCGJOGaUGvhDl/RtL9j4HhJDzUmT/dbZ4E9hMaAkfmZMz+KtrdVk/rZRW2+cXdcMIg0+dvIBAz1Gh7N8uiEjJ4U7AlltR+szdj/ZbAKq5eT4BKB6KXW4apiR5BqsLAgDfHpbq1Ot+S/SzPOx+SiEQjMsBe34l8vdO9HAhujmSvM=
  - secure: b8wGdKqlOKUGuLjeHGKk7D5mgYHlqwOJAWHlgdsGpCpvz82YRSsYIoOLD8cNPiJ7Jt0I2f9cMY6q8DwDwYML48CGYlXy3UYvUzkMBRR6ZPbp9lJCiMscWGrLwNLhUF27uS+/ZlRzEyslhBLJH9EdCbfPDy+t9XSFR6q2b5kR+aNcyyVirU/0DMzIB7gNzillo1ZTZEP5KYu43Z5B8cVwD+tGKTrPweaNyhQkt24V/lnhgmp4AqRQ/YdtpqBG8NN2Zmi4bRZHhzgu4pBUETzPqtdPC0u5829scYjxv2BWLPbfffxbByUG5jXwZwwaPE35Ccw1NMZRfyaBv6GlOBYtHvXBb+0Azeo4GYUdTBsgI7xMClGJPoRKn9WIKDukFf35ZUdJwPjzfEQjNml7OMzzDdTzVLO4Uq6h035+gyB0AZ1p0/7EeEZl06ZU2FjUTtFQV+AOFH8twGUIFkzm84NOfwFhdzPIGGzKBf0O7UiybuggKds51Ts87qE6m1aekG2AWspTFPsfHfVmxM7tDQ9U+ZoR+bHIkKj4OHmXRx4Xfg3cUBsKI8CSu9t3QQXdfSW+EzdQ4a7n9PKXYXZRCG+14tgVGwf4IaE4AXqCC5352LwIUA2AtKOX4CCgUWrGSCn3oJMm7lBQOe08Au5JfbqgQZSFiL72GmmOKGyXYhwkEuE=
deploy:
  provider: releases
  api_key:
    secure: '038nHViZ/EMfo7qc2zKeA5+WTF3H4v6rLy7wbZCf1ffZxakgbuDxRs0FICTngkBL/ot0c1N77HoqpamZ24NnKUH2t6OwZC4ZTmqdNkz3lbVUAi7C9qAiakcOD4BCAZDOxGs8FrZhB833G/iGL30Yd9zkMlzCniMBqnFh1DAiSLh+p6FcLUGU8h7NHJjDihzQkLD2MPJ+RghWVKeUlUU67F3v4vjDJnc/JNPrt+s3IzF4YCus7elJIX2dXzPZfqCENaRCScgA1vT/KUGI7FrUS6UZxuzJ0JG6VcyF0Mc/RVsFeDgLgpA4f9hbjheh9kh5hiiEB0RUWZ5u9zsWGb9TF/5gJDaFijXWv3rqnVKqQwjaJGUDNFYYwxAUookYyfT9OeYjNRpZ1gRPvprAl0wii2pTdrFXa+xpSjEmhjgjK3cOZWwUn0Kpqo9824O4QJSVYMRHpLncND4/WJ/gvAjUXO7mRm97vpt5klmGxlpF4hRnhZfxwXYVa1C/rIuz6sCNief/cidTf2ThKt2ZlE3pTHFCd0+bBDYp4POXHVeYNMN/uiORkUrQZwUslUNRQfZijRw9citaudjOIK3TxDloNrGBQgkuGgpdP/13t8+P77NdRFT/XQW/bFYkJMfvx7XwNuQQRuAXAlRtFW4Oq+EBSgujoEbRbD4VWvbA07gRw0Q='
  file: preston.jar
  skip_cleanup: true
  on:
    repo: bio-guoda/preston
    tags: true
